project:
  type: website
  title: Linguistic Convergence Laboratory
  output-dir: ./docs
  render:
  - index.qmd
  - resources.qmd
execute:
  echo: false
  warning: false
  message: false
format:
  html:
    theme: litera
lang: en
website:
  search: false
  page-footer: '![](images/hse_logo.png){width=12mm}<br>2021--2024, Linguistic Convergence
    Laboratory, HSE University'
  navbar:
    left:
    - text: ru
      href: ./ru/index.html
    right:
    - text: All resources
      href: ./resources.html
    - text: Dialect corpora
      menu: []
    - text: Bilingual Russian
      menu: []
    - text: Minority languages
      menu: []
    - text: Dictionaries
      menu: []
    - text: Other Resources
      menu: []

