project:
  type: website
  title: Resources of the Linguistic Convergence Laboratory
  output-dir: ./docs
  render:
  - index.qmd
  - resources.qmd
execute:
  echo: false
  warning: false
  message: false
format:
  html:
    theme: flatly
    linkcolor: '#2c3e50'
    header-includes: <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap"
      rel="stylesheet">
lang: en
mainfont: Open Sans
website:
  search: false
  favicon: images/favicon-32x32.png
  page-footer: '![](images/hse_logo.png){width=12mm}<br>2021--<span id=''year''></span>,
    Linguistic Convergence Laboratory, HSE University<script>document.getElementById(''year'').innerHTML
    = new Date().getFullYear();</script>'
  navbar:
    pinned: true
    right:
    - text: ru
      href: ./ru/index.html
  sidebar:
    style: docked
    background: dark
    collapse-level: 1.0
    contents:
    - text: Resources overview
      href: ./resources.html
    - section: Dialect corpora
      contents:
      - text: Don river dialects
        href: http://lingconlab.ru/don_rnd/
        content: 'Tokens: 69 098'
      - text: Ilmen Lake district dialects
        href: http://lingconlab.ru/novgorod/
        content: 'Tokens: 134 207'
      - text: Keba dialect
        href: http://lingconlab.ru/keba/
        content: 'Tokens: 54 535'
      - text: Khislavichi dialect
        href: http://lingconlab.ru/khislavichi/
        content: 'Tokens: 260 793'
      - text: Lukh and Teza river basins dialects
        href: http://lingconlab.ru/lukhteza/
        content: 'Tokens: 146 350'
      - text: Luzhnikovo dialect
        href: http://lingconlab.ru/luzhnikovo/
        content: 'Tokens: 68 666'
      - text: Malinino dialect
        href: http://lingconlab.ru/malinino/
        content: 'Tokens: 138 943'
      - text: Manturovo dialect
        href: http://lingconlab.ru/manturovo/
        content: 'Tokens: 113 837'
      - text: Middle Northern Dvina dialects
        href: http://lingconlab.ru/dvina/
        content: 'Tokens: 68 010'
      - text: Middle Pinega dialects
        href: http://lingconlab.ru/pinega/
        content: 'Tokens: 43 270'
      - text: Middle Pyoza dialect
        href: http://lingconlab.ru/pyoza/
        content: 'Tokens: 79 566'
      - text: Mikhaylov Corpus
        href: http://lingconlab.ru/mikhaylov/
        content: 'Tokens: 47 579'
      - text: Nekhochi dialect
        href: http://lingconlab.ru/nekhochi/
        content: 'Tokens: 88 965'
      - text: Opochetsky dialects
        href: http://lingconlab.ru/opochka/
        content: 'Tokens: 68 741'
      - text: Rogovatka dialect
        href: http://lingconlab.ru/rogovatka/
        content: 'Tokens: 100 047'
      - text: Shetnevo and Makeevo dialect
        href: http://lingconlab.ru/shetnevo/
        content: 'Tokens: 95 335'
      - text: Spiridonova Buda dialect
        href: http://lingconlab.ru/SpiridonovaBuda/
        content: 'Tokens: 70 565'
      - text: Svishni and Trostnoe dialects
        href: http://lingconlab.ru/yelets/
        content: 'Tokens: 24 414'
      - text: Tserkovnoe dialect
        href: http://lingconlab.ru/tserkovnoe/
        content: 'Tokens: 39 469'
      - text: Upper Pinega and Vyya river basins dialect
        href: http://lingconlab.ru/vaduga/
        content: 'Tokens: 70 803'
      - text: Ustja River Basin dialects
        href: http://www.parasolcorpus.org/Pushkino/
        content: 'Tokens: 959 782'
      - text: Veegora dialect
        href: http://lingconlab.ru/veegora/
        content: 'Tokens: 91 514'
      - text: Zvenigorod dialect
        href: http://lingconlab.ru/zvenigorod/
        content: 'Tokens: 68 324'
    - section: Corpora of bilingual Russian
      contents:
      - text: Bashkortostan Russian
        href: http://lingconlab.ru/BashkirRus/
        content: 'Tokens: 93 127'
      - text: Beserman Russian
        href: http://lingconlab.ru/BesermanRus/
        content: 'Tokens: 97 216'
      - text: Chuvash Russian
        href: http://lingconlab.ru/ChuvashRus/
        content: 'Tokens: 46 307'
      - text: Daghestanian Russian
        href: http://parasolcorpus.org/dagrus/
        content: 'Tokens: 376 717'
      - text: Karelian Russian
        href: http://lingconlab.ru/karelrus/
        content: 'Tokens: 578 646'
      - text: Mari Russian
        href: http://lingconlab.ru/MariRus/
        content: 'Tokens: 69 109'
      - text: Romani Russian
        href: http://lingconlab.ru/romarus/
        content: 'Tokens: 41 767'
      - text: Yakut Russian
        href: http://lingconlab.ru/cs_yakut/
        content: 'Tokens: 15 139'
    - section: Corpora of minority languages of Russia
      contents:
      - text: Abaza
        href: http://lingconlab.ru/spoken_abaza/
        content: 'Tokens: 3 636'
      - text: Bashkir
        href: http://lingconlab.ru/spoken_bashkir/
        content: 'Tokens: 28 202'
      - text: Besleney Kabardian
        href: http://lingconlab.ru/spoken_besleney/
        content: 'Tokens: 7 955'
      - text: Botlikh
        href: http://lingconlab.ru/botlikh/
        content: 'Tokens: 1 603'
      - text: Itsari Dargwa
        href: http://lingconlab.ru/itsari_dargwa/
        content: 'Tokens: 2 535'
      - text: Kadar Dargwa
        href: http://lingconlab.ru/kadar_dargwa/
        content: 'Tokens: 6 366'
      - text: Khakas
        href: http://lingconlab.ru/spoken_khakas/
        content: 'Tokens: 57 633'
      - text: Meadow Mari
        href: http://lingconlab.ru/spoken_meadow_mari/
        content: 'Tokens: 11 647'
      - text: Muira Dargwa
        href: http://lingconlab.ru/muira_dargwa/
        content: 'Tokens: 6 935'
      - text: Standard Dargwa
        href: http://lingconlab.ru/standard_dargwa/
        content: 'Tokens: 6 382 427'
      - text: Tanti Dargwa
        href: http://lingconlab.ru/tanti_dargwa/search
        content: 'Tokens: 2 683'
      - text: Tsnal Lezgi
        href: http://lingconlab.ru/tsnal_lezgi/
        content: 'Tokens: 5 113'
      - text: West Circassian
        href: http://lingconlab.ru/spoken_adyghe/
        content: 'Tokens: 9 128'
    - section: Dictionaries
      contents:
      - text: Dargwa varieties
        href: http://lingconlab.ru/dargwa_dict/
        content: 'Tokens: 7 917'
      - text: Khwarshi
        href: https://lingconlab.github.io/Khwarshi_dictionary/
        content: 'Tokens: 10 291'
      - text: Mehweb Dargwa
        href: http://lingconlab.ru/MehwebDict/
        content: 'Tokens: 1 132'
      - text: Rutul
        href: https://linghub.ru/rutuldict/
        content: 'Tokens: 738'
      - text: Tukita
        href: http://lingconlab.ru/TukitaDict/
        content: 'Tokens: 1 175'
    - section: Other Resources
      contents:
      - text: Atlas of Multilingualism in Dagestan
        href: https://multidagestan.com/
      - text: Atlas of Rutul dialects
        href: https://lingconlab.github.io/rutul_dialectology/
      - text: DAG < APT
        href: https://lingconlab.github.io/DAG-APT/
      - text: Daghestanian loans database
        href: http://lingconlab.ru/dagloans/
      - text: DagSwadesh
        href: http://lingconlab.ru/dagswadesh/
      - text: Parabible
        href: http://lingconlab.ru/parabible/
      - text: Prosody of Russian Dialects
        href: https://lingconlab.github.io/PRuD/
      - text: The Andic Dictionaries Examples Database
        href: https://lingconlab.github.io/andic_dictionary_examples_database/
      - text: Typological Atlas of the Languages of Daghestan
        href: http://lingconlab.ru/dagatlas/

