project:
  type: website
  title: Ресурсы Международной лаборатории языковой конвергенции
  output-dir: ./../docs/ru
  render:
  - index.qmd
  - resources.qmd
execute:
  echo: false
  warning: false
  message: false
format:
  html:
    theme: flatly
    linkcolor: '#2c3e50'
    header-includes: <link rel="preconnect" href="https://fonts.gstatic.com"><link
      href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap"
      rel="stylesheet">
lang: ru
mainfont: Open Sans
website:
  search: false
  favicon: ../images/favicon-32x32.png
  page-footer: '![](../images/hse_logo.png){width=12mm}<br>2021--<span id=''year''></span>,
    Международная лаборатория языковой конвергенции, НИУ ВШЭ<script>document.getElementById(''year'').innerHTML
    = new Date().getFullYear();</script>'
  navbar:
    pinned: true
    right:
    - text: en
      href: ./../index.html
  sidebar:
    style: docked
    background: dark
    collapse-level: 1.0
    contents:
    - text: Обзор ресурсов
      href: ./resources.html
    - section: Диалектные корпуса
      contents:
      - text: Говор Средней Пёзы
        href: http://lingconlab.ru/pyoza/
      - text: Говор верхней Пинеги и Выи
        href: http://lingconlab.ru/vaduga/
      - text: Говор г. Звенигород
        href: http://lingconlab.ru/zvenigorod/
      - text: Говор д. Веегора
        href: http://lingconlab.ru/veegora/
      - text: Говор д. Нехочи
        href: http://lingconlab.ru/nekhochi/
      - text: Говор д. Шетнево и Макеево
        href: http://lingconlab.ru/shetnevo/
      - text: Говор с. Кеба
        href: http://lingconlab.ru/keba/
      - text: Говор с. Малинино
        href: http://lingconlab.ru/malinino/
      - text: Говор с. Роговатка
        href: http://lingconlab.ru/rogovatka/
      - text: Говор с. Спиридонова Буда
        href: http://lingconlab.ru/SpiridonovaBuda/
      - text: Говор с. Церковное
        href: http://lingconlab.ru/tserkovnoe/
      - text: Говор сёл Свишни и Тростное
        href: http://lingconlab.ru/yelets/
      - text: Говоры  среднего течения Пинеги
        href: http://lingconlab.ru/pinega/
      - text: Говоры низовья рек Лух и Теза
        href: http://lingconlab.ru/lukhteza/
      - text: Говоры среднего течения Северной Двины
        href: http://lingconlab.ru/dvina/
      - text: Донские говоры
        href: http://lingconlab.ru/don_rnd/
      - text: Корпус Михайлова
        href: http://lingconlab.ru/mikhaylov/
      - text: Лужниковский говор
        href: http://lingconlab.ru/luzhnikovo/
      - text: Мантуровский говор
        href: http://lingconlab.ru/manturovo/
      - text: Опочецкие говоры
        href: http://lingconlab.ru/opochka/
      - text: Устьянские говоры
        href: http://www.parasolcorpus.org/Pushkino/
      - text: Хиславичский говор
        href: http://lingconlab.ru/khislavichi/
    - section: Корпуса билингвального русского
      contents:
      - text: Башкирский русский
        href: http://lingconlab.ru/BashkirRus/
      - text: Бесермянский русский
        href: http://lingconlab.ru/BesermanRus/
      - text: Дагестанский русский
        href: http://parasolcorpus.org/dagrus/
      - text: Карельский русский
        href: http://lingconlab.ru/karelrus/
      - text: Марийский русский
        href: http://lingconlab.ru/MariRus/
      - text: Цыганский русский
        href: http://lingconlab.ru/romarus/
      - text: Чувашский русский
        href: http://lingconlab.ru/ChuvashRus/
      - text: Якутский русский
        href: http://lingconlab.ru/cs_yakut/
    - section: Малые языки России
      contents:
      - text: Абазинский язык
        href: http://lingconlab.ru/spoken_abaza/
      - text: Адыгейский язык
        href: http://lingconlab.ru/spoken_adyghe/
      - text: Башкирский язык
        href: http://lingconlab.ru/spoken_bashkir/
      - text: Ботлихский язык
        href: http://lingconlab.ru/botlikh/
      - text: Ицаринский даргинский
        href: http://lingconlab.ru/itsari_dargwa/
      - text: Кабардино-черкесский язык
        href: http://lingconlab.ru/spoken_besleney/
      - text: Кадарский даргинский
        href: http://lingconlab.ru/kadar_dargwa/
      - text: Литературный даргинский язык
        href: http://lingconlab.ru/standard_dargwa/
      - text: Луговой марийский язык
        href: http://lingconlab.ru/spoken_meadow_mari/
      - text: Малокарачкинского говор чувашского языка
        href: http://lingconlab.ru/chuvash/
      - text: Муиринский даргинский
        href: http://lingconlab.ru/muira_dargwa/
      - text: Тантынский даргинский
        href: http://lingconlab.ru/tanti_dargwa/search
      - text: Хакасский язык
        href: http://lingconlab.ru/spoken_khakas/
      - text: Цнальский диалект лезгинского языка
        href: http://lingconlab.ru/tsnal_lezgi/
    - section: Словари
      contents:
      - text: Даргинские языки
        href: http://lingconlab.ru/dargwa_dict/
      - text: Мегебский язык
        href: http://lingconlab.ru/MehwebDict/
      - text: Рутульский язык
        href: https://linghub.ru/rutuldict/
      - text: Тукитинский язык
        href: http://lingconlab.ru/TukitaDict/
      - text: Хваршинский язык
        href: https://lingconlab.github.io/Khwarshi_dictionary/
    - section: Другие проекты
      contents:
      - text: DAG < APT
        href: https://lingconlab.github.io/DAG-APT/
      - text: DagSwadesh
        href: http://lingconlab.ru/dagswadesh/
      - text: Parabible
        href: http://lingconlab.ru/parabible/
      - text: Атлас диалектов рутульского языка
        href: https://lingconlab.github.io/rutul_dialectology/
      - text: Атлас многоязычия в Дагестане
        href: https://multidagestan.com/
      - text: База данных заимствований в языках Дагестана
        href: http://lingconlab.ru/dagloans/
      - text: База данных примеров андийских словарей
        href: https://lingconlab.github.io/andic_dictionary_examples_database/
      - text: База данных просодии русских диалектов
        href: https://lingconlab.github.io/PRuD/
      - text: Типологический атлас языков Дагестана
        href: http://lingconlab.ru/dagatlas/

