project:
  type: website
  title: Международная лаборатория языковой конвергенции
  output-dir: ./../docs/ru
  render:
  - index.qmd
  - resources.qmd
execute:
  echo: false
  warning: false
  message: false
format:
  html:
    theme: litera
lang: ru
website:
  search: false
  page-footer: '![](../images/hse_logo.png){width=12mm}<br>2021--2024, Международная
    лаборатория языковой конвергенции, НИУ ВШЭ'
  navbar:
    left:
    - text: en
      href: ./../index.html
    right:
    - text: Все ресурсы
      href: ./resources.html
    - text: Диалектные корпуса
      menu: []
    - text: Билингвальный русский
      menu: []
    - text: Малые языки
      menu: []
    - text: Словари
      menu: []
    - text: Другие проекты
      menu: []

