project:
  type: website
  title: Ресурсы Международной лаборатории языковой конвергенции
  output-dir: ./../docs/ru
  render:
  - index.qmd
  - resources.qmd
execute:
  echo: false
  warning: false
  message: false
format:
  html:
    theme: flatly
    linkcolor: '#2c3e50'
    header-includes: <link rel="preconnect" href="https://fonts.gstatic.com"><link
      href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap"
      rel="stylesheet">
lang: ru
mainfont: Open Sans
website:
  search: false
  favicon: ../images/favicon-32x32.png
  page-footer: '![](../images/hse_logo.png){width=12mm}<br>2021--<span id=''year''></span>,
    Международная лаборатория языковой конвергенции, НИУ ВШЭ<script>document.getElementById(''year'').innerHTML
    = new Date().getFullYear();</script>'
  navbar:
    right:
    - text: en
      href: ./../index.html
  sidebar:
    style: docked
    background: dark
    collapse-level: 1.0
    contents:
    - text: Обзор ресурсов
      href: ./resources.html
    - section: Диалектные корпуса
      contents:
      - text: Корпус говора Мантуровского района Костромской области
        href: http://lingconlab.ru/manturovo/
      - text: Корпус говора Средней Пёзы
        href: http://lingconlab.ru/pyoza/
      - text: Корпус говора Хиславичского района
        href: http://lingconlab.ru/khislavichi/
      - text: Корпус говора верхней Пинеги и Выи
        href: http://lingconlab.ru/vaduga/
      - text: Корпус говора города Звенигород
        href: http://lingconlab.ru/zvenigorod/
      - text: Корпус говора деревень Шетнево и Макеево
        href: http://lingconlab.ru/shetnevo/
      - text: Корпус говора деревни Веегора
        href: http://lingconlab.ru/veegora/
      - text: Корпус говора деревни Нехочи
        href: http://lingconlab.ru/nekhochi/
      - text: Корпус говора села Кеба
        href: http://lingconlab.ru/keba/
      - text: Корпус говора села Малинино
        href: http://lingconlab.ru/malinino/
      - text: Корпус говора села Роговатка
        href: http://lingconlab.ru/rogovatka/
      - text: Корпус говора села Спиридонова Буда
        href: http://lingconlab.ru/SpiridonovaBuda/
      - text: Корпус говора села Церковное
        href: http://lingconlab.ru/tserkovnoe/
      - text: Корпус говоров Средней Пинеги
        href: http://lingconlab.ru/pinega/
      - text: Корпус говоров низовья рек Лух и Теза
        href: http://lingconlab.ru/lukhteza/
      - text: Корпус говоров окрестностей Михайлова
        href: http://lingconlab.ru/mikhaylov/
      - text: Корпус говоров среднего течения Северной Двины
        href: http://lingconlab.ru/dvina/
      - text: Корпус донских говоров
        href: http://lingconlab.ru/don_rnd/
      - text: Корпус опочецких говоров
        href: http://lingconlab.ru/opochka/
      - text: Корпус сёл Свишни и Тростное
        href: http://lingconlab.ru/yelets/
      - text: Корпус устьянских говоров
        href: http://www.parasolcorpus.org/Pushkino/
      - text: Лужниковский корпус
        href: http://lingconlab.ru/luzhnikovo/
    - section: Корпуса билингвального русского
      contents:
      - text: Корпус дагестанского русского
        href: http://parasolcorpus.org/dagrus/
      - text: Корпус русской речи Башкирии
        href: http://lingconlab.ru/BashkirRus/
      - text: Корпус русской речи Карелии
        href: http://lingconlab.ru/karelrus/
      - text: Корпус русской речи Чувашии
        href: http://lingconlab.ru/ChuvashRus/
      - text: Корпус русской речи бесермян
        href: http://lingconlab.ru/BesermanRus/
      - text: Корпус русской речи республики Марий Эл
        href: http://lingconlab.ru/MariRus/
      - text: Корпус цыганского русского
        href: http://lingconlab.ru/romarus/
      - text: Якутско-русский корпус переключения кода
        href: http://lingconlab.ru/cs_yakut/
    - section: Малые языки России
      contents:
      - text: Корпус литературного даргинского
        href: http://lingconlab.ru/standard_dargwa/
      - text: Устный корпус абазинского языка
        href: http://lingconlab.ru/spoken_abaza/
      - text: Устный корпус адыгейского языка
        href: http://lingconlab.ru/spoken_adyghe/
      - text: Устный корпус башкирского языка
        href: http://lingconlab.ru/spoken_bashkir/
      - text: Устный корпус бесленеевского диалекта кабардино-черкесского языка
        href: http://lingconlab.ru/spoken_besleney/
      - text: Устный корпус ботлихского языка
        href: http://lingconlab.ru/botlikh/
      - text: Устный корпус диалектов хакасского языка
        href: http://lingconlab.ru/spoken_khakas/
      - text: Устный корпус ицаринского даргинского
        href: http://lingconlab.ru/itsari_dargwa/
      - text: Устный корпус кадарского даргинского
        href: http://lingconlab.ru/kadar_dargwa/
      - text: Устный корпус лугового марийского языка
        href: http://lingconlab.ru/spoken_meadow_mari/
      - text: Устный корпус малокарачкинского говора чувашского языка
        href: http://lingconlab.ru/chuvash/
      - text: Устный корпус муиринского даргинского
        href: http://lingconlab.ru/muira_dargwa/
      - text: Устный корпус тантынского даргинского
        href: http://lingconlab.ru/tanti_dargwa/search
      - text: Устный корпус цнальского говора лезгинского языка
        href: http://lingconlab.ru/tsnal_lezgi/
    - section: Словари
      contents:
      - text: Словарь даргинских языков
        href: http://lingconlab.ru/dargwa_dict/
      - text: Словарь мегебского языка
        href: http://lingconlab.ru/MehwebDict/
      - text: Словарь рутульского языка
        href: https://linghub.ru/rutuldict/
      - text: Словарь тукитинского языка
        href: http://lingconlab.ru/TukitaDict/
      - text: Словарь хваршинского языка
        href: https://lingconlab.github.io/Khwarshi_dictionary/
    - section: Другие проекты
      contents:
      - text: DAG < APT
        href: https://lingconlab.github.io/DAG-APT/
      - text: DagSwadesh
        href: http://lingconlab.ru/dagswadesh/
      - text: Parabible
        href: http://lingconlab.ru/parabible/
      - text: Атлас диалектов рутульского языка
        href: https://lingconlab.github.io/rutul_dialectology/
      - text: Атлас многоязычия в Дагестане
        href: https://multidagestan.com/
      - text: База данных заимствований в языках Дагестана
        href: http://lingconlab.ru/dagloans/
      - text: База данных примеров андийских словарей
        href: https://lingconlab.github.io/andic_dictionary_examples_database/
      - text: База данных просодии русских диалектов
        href: https://lingconlab.github.io/PRuD/
      - text: Типологический атлас языков Дагестана
        href: http://lingconlab.ru/dagatlas/

